// Generated by the protocol buffer compiler.  DO NOT EDIT!

#include "messages_robocup_ssl_geometry.pb.h"
#include <google/protobuf/descriptor.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format_inl.h>

namespace {


}  // namespace


void protobuf_BuildDesc_messages_5frobocup_5fssl_5fgeometry_2eproto_AssignGlobalDescriptors(const ::google::protobuf::FileDescriptor* file) {
}

void protobuf_BuildDesc_messages_5frobocup_5fssl_5fgeometry_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;
  ::google::protobuf::DescriptorPool* pool =
    ::google::protobuf::DescriptorPool::internal_generated_pool();

  pool->InternalBuildGeneratedFile(
    "\n#messages_robocup_ssl_geometry.proto", 37,
  &protobuf_BuildDesc_messages_5frobocup_5fssl_5fgeometry_2eproto_AssignGlobalDescriptors);
}

// Force BuildDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_messages_5frobocup_5fssl_5fgeometry_2eproto {
  StaticDescriptorInitializer_messages_5frobocup_5fssl_5fgeometry_2eproto() {
    protobuf_BuildDesc_messages_5frobocup_5fssl_5fgeometry_2eproto();
  }
} static_descriptor_initializer_messages_5frobocup_5fssl_5fgeometry_2eproto_;

